### PR TITLE
Most of the way to supporting conditionals. Still needs revert to work

### LINKED ISSUE #8: Handle conditional packages
Need to handle conditional packages and write to the central file with that condition.

See: https://gist.github.com/axelheer/da455edebbd64f6c20bce962542d06bb

### PR DESCRIPTION
**Pull request by belav**
We have a huge work solution with 190 projects + conditions on a lot of the packages. It made sense for me to modify this to support conditions. 
I will hopefully find the time to get back to this and finish up support for revert, but I won't be offended it you take it from here.

closes #8

### CODE REVIEW

**Comment by belav** [comment]
I take it back, I didn't actually test the compile of our solution before submitting this PR, so I will be working on this more today!

**Comment by Webreaper** [comment]
I haven't got time to review this or test it right now. I might not be able to look at it for a couple of months. @davidwengier or @ThomasArdal - are you able to have a look?

Alternatively, if you're confident it's in a good enough shape, @belav, I'm happy to merge it. #yolo

**Review by davidwengier — APPROVED** [review]
The `textNode.Remote()` is a little scary, as I'm not sure that would always match on whitespace, but anyone who runs this and doesn't check the results deserves what they get anyway :)

Fantastic tests though!! Nice one.

**Comment by Webreaper** [comment]
Thanks @davidwengier !! Merged.

**Pull request merged**
