### PR TITLE
NuGetVersion, pick lowest option, directory excludes, tests

### PR DESCRIPTION
**Pull request by BastianBirke**
- Version comparison by _NuGetVersion_ (configurable by command line option)
- Directory filtering by regex: _.*, bin, obj_.
  - _DirectoryCrawler_ class
- Optional pick of lowest version
- Can ignore prerelease versions.

### CODE REVIEW

**Comment by BastianBirke** [comment]
I finished my adaptions to the converter some time ago, shall this PR be merged back? @Webreaper

**Comment by Webreaper** [comment]
Sorry, last week or so has been a bit frantic. Will have a look at this and merge in the next few days!

**Comment by rstm-sf** [comment]
@Webreaper ping :)

**Comment by Webreaper** [comment]
Pong!

**Pull request merged**
